version: "3.5"

services:
  api01:
    build: ./
    hostname: api01
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "750MB"

  api02:
    build: ./
    hostname: api02
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "750MB"

  nginx:
    # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "500MB"

  db:
    image: mongo:latest
    hostname: db
    environment:
      - MONGO_INITDB_DATABASE=person_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: mongod --quiet --logpath /dev/null
    volumes:
      - ./dbdata:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "1072MB"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  default:
    driver: bridge
    name: rinha
