version: "3.5"

services:
  api01:
    build: ./
    hostname: api01
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "0.75GB"

  api02:
    build: ./
    hostname: api02
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "0.75GB"

  nginx:
    # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.25GB"

  db:
    image: mongo:latest
    hostname: db
    environment:
      - MONGO_INITDB_DATABASE=person_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.25GB"

  # redis:
  #   image: redis:latest
  #   hostname: redis
  #   ports:
  #     - "6379:6379"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.02"
  #         memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha
